In [49]:
import numpy as np
from scipy.stats import ortho_group
U=ortho_group.rvs(3) #orthogonal matrix
#print(U)

D=np.diag(np.diag(U)) #diagonal matrix
print(D)

A=np.matmul(np.matmul(U.T,D),U)
print(A)

b=A[:,0]+A[:,1]+A[:,2]
print(b)


[[-0.61176393  0.          0.        ]
 [ 0.          0.64836613  0.        ]
 [ 0.          0.          0.28907312]]
[[-0.03080966  0.21942473 -0.39929938]
 [ 0.21942473  0.22310911  0.44413205]
 [-0.39929938  0.44413205  0.13337587]]
[-0.21068432  0.88666588  0.17820853]


In [48]:
import numpy as np
from scipy.stats import ortho_group
from numpy.linalg import norm
from matplotlib import pyplot
import math

B=np.random.random((100, 100)) #random matrix


A=np.matmul(B.T,B) #should be 100*100
#print(A)

b=A[:,0]+A[:,1]+A[:,2] #should be 100*1
#print(b)



In [49]:
def objective(x):
    return np.matmul(np.matmul(x.T,A),x)-np.matmul(b.T,x)
    
def derivative(x):
    return 0.5*np.matmul(A.T,x)+0.5*np.matmul(A,x)-b

In [53]:

def gradient_descent(objective, derivative, start, learn_rate, n_iter, tolerance):
     # track all solutions
    solutions, scores = list(), list()
    solution = start
    for i in range(n_iter):
        #calculate gradient
        gradient=derivative(solution)
        if (norm(gradient,2) <= tolerance):
            break
        solution = solution - learn_rate * gradient
        solution_eval= objective(solution)
        
         # store solution
        solutions.append(solution)
        scores.append(solution_eval)
        
         # report progress
        print('>%d f(%s) = %.5f' % (i, solution, solution_eval)) #value at each iteration
        
    return [solutions,scores,solution]

#implementation
learn_rate=0.2
n_iter = 100
tolerance=10e-5

start = np.random.uniform(-1,1,(100,)) #starting point
# perform the gradient descent search
solutions, scores, solution = gradient_descent(objective, derivative, start, learn_rate, n_iter, tolerance)


>0 f([-17.97592238 -19.11707033 -19.13460299 -21.19324722 -17.29173674
 -20.62709805 -19.79614486 -24.04539037 -18.44059159 -21.74268042
 -18.55638853 -17.72831362 -20.73062002 -22.12812394 -18.6646928
 -20.45509366 -19.87058313 -17.96979717 -21.57689574 -17.12183718
 -22.29414325 -21.6094723  -19.04633681 -22.57480664 -20.87752686
 -20.67991303 -18.39460565 -20.88962265 -21.84201552 -17.19593568
 -20.77513419 -21.01931825 -20.70048162 -21.07200666 -18.96213678
 -17.31305511 -20.05165411 -19.04420695 -21.33018562 -20.66801774
 -20.33479803 -22.25894517 -18.90360099 -19.21099744 -20.98211697
 -20.62742272 -22.3932103  -19.78186753 -20.93167108 -21.1361434
 -21.48992977 -18.69402755 -18.30480516 -21.9545082  -18.37949412
 -21.03844539 -20.64330315 -19.69158245 -18.71387333 -19.78218604
 -20.59252264 -19.25317432 -21.79171666 -19.31702583 -20.42449694
 -20.51940786 -20.88869168 -17.97093014 -20.91630322 -21.36602488
 -23.4424761  -21.17388245 -22.61246478 -16.64216432 -20.81727386
 -21.57

c:\users\zangp\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in matmul
  


In [57]:
#matrix of optimal solutions
print(solution)
#opt_matrix=np.full((100, 1), solution)
print(solution.shape)


[5.81134854e+268 6.26260232e+268 6.15632905e+268 6.00683437e+268
 5.18484783e+268 6.09348003e+268 6.05229809e+268 6.66855025e+268
 5.56349569e+268 6.29406418e+268 5.80630699e+268 5.20140965e+268
 5.92511629e+268 6.78588940e+268 5.62141992e+268 5.97434887e+268
 5.61732147e+268 5.25502719e+268 6.14508729e+268 5.56080812e+268
 6.31701193e+268 6.54538385e+268 5.76405888e+268 6.28014629e+268
 5.99626233e+268 6.34625895e+268 5.93676621e+268 6.05224824e+268
 6.55536735e+268 5.89011241e+268 5.59009979e+268 6.25223048e+268
 6.35436321e+268 6.07774835e+268 6.01453377e+268 5.54992992e+268
 6.24185639e+268 5.68898209e+268 6.47906465e+268 5.79847309e+268
 6.48096985e+268 6.37922666e+268 5.65328614e+268 5.67087875e+268
 6.12455745e+268 5.77916171e+268 6.52488762e+268 5.90523656e+268
 6.34317290e+268 6.35861503e+268 6.65334350e+268 5.33660766e+268
 5.76578120e+268 5.81704922e+268 5.58185866e+268 5.90096123e+268
 6.30595167e+268 5.67580072e+268 5.72332871e+268 6.00249685e+268
 6.19331749e+268 5.949357

In [60]:
opt_matrix=np.full((100, 100), solution)

In [66]:
differences=math.log(norm(solutions-opt_matrix,2, 1))
print(differences.shape)
#gradient descent iterations
iterations=np.arange(1,len(solutions)+1)
# plot the solutions found
pyplot.plot(iterations, differences, '.-', color='red')
# show the plot
pyplot.show()

TypeError: only size-1 arrays can be converted to Python scalars

<class 'list'>
